UIC: SubSidebar
mnir29/assisdent-web-client pull request #27
Opened 2023-03-13 14:28 UTC by kalakaveri

## Muutokset ja syyt muutoksille?

UIC: SubSidebar. Sidebarin haku ja sen toiminnallisuudet

## Muutoksien testaus

npm run dev

## Kuvakaappaus
![UIC SubSideBar-Haku (1)](https://user-images.githubusercontent.com/55297499/224730757-e555072d-95fe-4a63-9605-3b9c2b9814ef.jpg)
![UIC SubSideBar-Haku (2)](https://user-images.githubusercontent.com/55297499/224730764-c1d30212-c38f-4e3f-9469-908f7ede1340.jpg)
![UIC SubSideBar-Haku (3)](https://user-images.githubusercontent.com/55297499/224730769-b5f506c1-5f00-45b5-b9ce-00c80745bcf7.jpg)

2023-03-17 10:55 UTC, mnir29 approved these changes

2023-03-17 13:25 UTC, mnir29 requested changes
Jotakin merge conflictia on developmentin kanssa vielä

2023-03-19 11:09 UTC, kalakaveri commented
Oiskohan se siinä

2023-03-20 07:39 UTC, petrikreus commented
Odotetaan et mergetään eka #33 ja katotaan sit uudestaan merge conflictit tästä

2023-03-20 08:24 UTC, merged